# Classifying Penguins with Keras

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [3]:
! pip install palmerpenguins
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins.head()

Collecting palmerpenguins
  Downloading palmerpenguins-0.1.6-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: pandas in C:\Users\ivpri\gsb545\.venv_clean\Lib\site-packages (from palmerpenguins) (3.0.2)
Requirement already satisfied: numpy in C:\Users\ivpri\gsb545\.venv_clean\Lib\site-packages (from palmerpenguins) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ivpri\gsb545\.venv_clean\Lib\site-packages (from pandas->palmerpenguins) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ivpri\gsb545\.venv_clean\Lib\site-packages (from pandas->palmerpenguins) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\ivpri\gsb545\.venv_clean\Lib\site-packages (from python-dateutil>=2.8.2->pandas->palmerpenguins) (1.17.0)
Downloading palmerpenguins-0.1.6-py3-none-any.whl (18 kB)
Installing collected packages: palmerpenguins
Successfully installed palmerpenguins-0.1.6

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [4]:
penguins = penguins.dropna()
penguins.shape

(333, 8)

In [5]:
# shuffle the data
penguins = penguins.sample(frac=1, random_state=42).reset_index(drop=True)

In [6]:
penguins_x = pd.concat([penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,3250.0,39.5,16.7,178.0,True,False
1,3675.0,50.9,17.9,196.0,True,False
2,4000.0,42.1,19.1,195.0,False,True
3,4850.0,46.6,14.2,210.0,True,False
4,4050.0,41.1,18.2,192.0,False,True
...,...,...,...,...,...,...
328,4750.0,49.6,15.0,216.0,False,True
329,3900.0,37.2,19.4,184.0,False,True
330,3200.0,39.7,17.7,193.0,True,False
331,3950.0,45.2,17.8,198.0,True,False
332,3175.0,38.1,17.0,181.0,True,False

In [7]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,0.152778,0.269091,0.428571,0.101695,1.0,0.0
1,0.270833,0.683636,0.571429,0.406780,1.0,0.0
2,0.361111,0.363636,0.714286,0.389831,0.0,1.0
3,0.597222,0.527273,0.130952,0.644068,1.0,0.0
4,0.375000,0.327273,0.607143,0.338983,0.0,1.0
...,...,...,...,...,...,...
328,0.569444,0.636364,0.226190,0.745763,0.0,1.0
329,0.333333,0.185455,0.750000,0.203390,0.0,1.0
330,0.138889,0.276364,0.547619,0.355932,1.0,0.0
331,0.347222,0.476364,0.559524,0.440678,1.0,0.0
332,0.131944,0.218182,0.464286,0.152542,1.0,0.0

In [8]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()
penguins_y

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: str

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0,
       0, 1, 0], dtype=int8)

In [9]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
outputs = layers.Dense(3, activation='sigmoid')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [10]:
model.summary()

Model: "penguin_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 7)              │            49 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119 (476.00 B)

 Trainable params: 119 (476.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) for `plot_model` to work.

In [13]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs=100, validation_split=0.1)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=2)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Epoch 1/100

c:\Users\ivpri\gsb545\.venv_clean\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

1/5 ━━━━━━━━━━━━━━━━━━━━ 12s 3s/step - accuracy: 0.1250 - loss: 1.1456

c:\Users\ivpri\gsb545\.venv_clean\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 4s 204ms/step - accuracy: 0.1271 - loss: 1.1355 - val_accuracy: 0.1765 - val_loss: 1.1384
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.1304 - loss: 1.1252 - val_accuracy: 0.0882 - val_loss: 1.1319
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.2441 - loss: 1.1186 - val_accuracy: 0.3824 - val_loss: 1.1264
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.4448 - loss: 1.1132 - val_accuracy: 0.3824 - val_loss: 1.1214
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4448 - loss: 1.1081 - val_accuracy: 0.3824 - val_loss: 1.1165
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.4448 - loss: 1.1032 - val_accuracy: 0.3824 - val_loss: 1.1123
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.4448 - loss: 1.0986 - val_accuracy: 0.3824 - val_loss: 1.1079
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4448 - loss: 1.0948 - val_accuracy: 0.3824 - val_loss: 1.1043
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.4448 - loss: 1.0912 - val_accuracy: 0.3824 - val_loss: 1.1011
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.4448 - loss: 1.0878 - val_accuracy: 0.3824 - val_loss: 1.0979
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.4448 - loss: 1.0846 - val_accuracy: 0.3824 - val_loss: 1.0952
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.4448 - loss: 1.0819 - val_accuracy: 0.3824 - val_loss: 1.0927
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.4448 - loss: 1.0792 - val_accuracy: 0.3824 - val_loss: 1.0905
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.4448 - loss: 1.0765 - val_accuracy: 0.3824 - val_loss: 1.0882
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4448 - loss: 1.0738 - val_accuracy: 0.3824 - val_loss: 1.0858
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4448 - loss: 1.0710 - val_accuracy: 0.3824 - val_loss: 1.0832
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4448 - loss: 1.0683 - val_accuracy: 0.3824 - val_loss: 1.0806
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4448 - loss: 1.0657 - val_accuracy: 0.3824 - val_loss: 1.0776
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.4448 - loss: 1.0624 - val_accuracy: 0.3824 - val_loss: 1.0751
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4448 - loss: 1.0593 - val_accuracy: 0.3824 - val_loss: 1.0720
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.4448 - loss: 1.0559 - val_accuracy: 0.3824 - val_loss: 1.0687
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.4448 - loss: 1.0522 - val_accuracy: 0.3824 - val_loss: 1.0653
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.4448 - loss: 1.0481 - val_accuracy: 0.3824 - val_loss: 1.0617
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.4482 - loss: 1.0436 - val_accuracy: 0.3824 - val_loss: 1.0578
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.4482 - loss: 1.0388 - val_accuracy: 0.3824 - val_loss: 1.0536
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4482 - loss: 1.0338 - val_accuracy: 0.3824 - val_loss: 1.0488
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.4515 - loss: 1.0285 - val_accuracy: 0.3824 - val_loss: 1.0443
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.4515 - loss: 1.0230 - val_accuracy: 0.3824 - val_loss: 1.0393
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.4615 - loss: 1.0175 - val_accuracy: 0.3824 - val_loss: 1.0347
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4582 - loss: 1.0120 - val_accuracy: 0.3824 - val_loss: 1.0292
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 93ms/step - accuracy: 0.5050 - loss: 1.0062 - val_accuracy: 0.3824 - val_loss: 1.0243
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5017 - loss: 1.0003 - val_accuracy: 0.4118 - val_loss: 1.0188
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5151 - loss: 0.9944 - val_accuracy: 0.4118 - val_loss: 1.0126
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5619 - loss: 0.9882 - val_accuracy: 0.4412 - val_loss: 1.0069
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5719 - loss: 0.9817 - val_accuracy: 0.4706 - val_loss: 1.0004
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5819 - loss: 0.9756 - val_accuracy: 0.5000 - val_loss: 0.9944
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5987 - loss: 0.9686 - val_accuracy: 0.5000 - val_loss: 0.9878
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6154 - loss: 0.9619 - val_accuracy: 0.5294 - val_loss: 0.9810
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6288 - loss: 0.9551 - val_accuracy: 0.5294 - val_loss: 0.9744
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6288 - loss: 0.9482 - val_accuracy: 0.5588 - val_loss: 0.9669
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6555 - loss: 0.9410 - val_accuracy: 0.5882 - val_loss: 0.9593
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.6789 - loss: 0.9315 - val_accuracy: 0.5882 - val_loss: 0.9474
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6957 - loss: 0.9196 - val_accuracy: 0.5882 - val_loss: 0.9362
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7124 - loss: 0.9091 - val_accuracy: 0.6471 - val_loss: 0.9258
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7258 - loss: 0.8994 - val_accuracy: 0.6471 - val_loss: 0.9152
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7425 - loss: 0.8902 - val_accuracy: 0.6471 - val_loss: 0.9062
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7525 - loss: 0.8814 - val_accuracy: 0.6765 - val_loss: 0.8965
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7692 - loss: 0.8722 - val_accuracy: 0.7647 - val_loss: 0.8869
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7759 - loss: 0.8636 - val_accuracy: 0.7647 - val_loss: 0.8773
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7826 - loss: 0.8548 - val_accuracy: 0.7647 - val_loss: 0.8680
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7893 - loss: 0.8457 - val_accuracy: 0.7647 - val_loss: 0.8573
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7926 - loss: 0.8365 - val_accuracy: 0.7647 - val_loss: 0.8491
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7893 - loss: 0.8273 - val_accuracy: 0.7647 - val_loss: 0.8401
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7926 - loss: 0.8180 - val_accuracy: 0.7647 - val_loss: 0.8297
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7893 - loss: 0.8086 - val_accuracy: 0.7941 - val_loss: 0.8188
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7926 - loss: 0.7990 - val_accuracy: 0.7941 - val_loss: 0.8072
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7926 - loss: 0.7897 - val_accuracy: 0.7941 - val_loss: 0.7953
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7926 - loss: 0.7808 - val_accuracy: 0.7941 - val_loss: 0.7861
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7926 - loss: 0.7716 - val_accuracy: 0.7941 - val_loss: 0.7787
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7926 - loss: 0.7624 - val_accuracy: 0.7941 - val_loss: 0.7680
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7926 - loss: 0.7534 - val_accuracy: 0.7941 - val_loss: 0.7582
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7926 - loss: 0.7443 - val_accuracy: 0.7941 - val_loss: 0.7454
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7926 - loss: 0.7349 - val_accuracy: 0.7941 - val_loss: 0.7379
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7926 - loss: 0.7256 - val_accuracy: 0.7941 - val_loss: 0.7267
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7926 - loss: 0.7162 - val_accuracy: 0.7941 - val_loss: 0.7154
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7960 - loss: 0.7074 - val_accuracy: 0.7941 - val_loss: 0.7063
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7926 - loss: 0.6975 - val_accuracy: 0.7941 - val_loss: 0.6955
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7960 - loss: 0.6879 - val_accuracy: 0.7941 - val_loss: 0.6839
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7960 - loss: 0.6787 - val_accuracy: 0.7941 - val_loss: 0.6737
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7960 - loss: 0.6687 - val_accuracy: 0.7941 - val_loss: 0.6640
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7960 - loss: 0.6601 - val_accuracy: 0.7941 - val_loss: 0.6541
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7960 - loss: 0.6506 - val_accuracy: 0.7941 - val_loss: 0.6443
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7960 - loss: 0.6423 - val_accuracy: 0.7941 - val_loss: 0.6349
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7960 - loss: 0.6324 - val_accuracy: 0.7941 - val_loss: 0.6262
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7960 - loss: 0.6238 - val_accuracy: 0.7941 - val_loss: 0.6164
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7960 - loss: 0.6149 - val_accuracy: 0.7941 - val_loss: 0.6072
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7960 - loss: 0.6058 - val_accuracy: 0.7941 - val_loss: 0.5972
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7960 - loss: 0.5967 - val_accuracy: 0.7941 - val_loss: 0.5875
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7960 - loss: 0.5885 - val_accuracy: 0.7941 - val_loss: 0.5779
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7960 - loss: 0.5793 - val_accuracy: 0.7941 - val_loss: 0.5684
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7960 - loss: 0.5710 - val_accuracy: 0.7941 - val_loss: 0.5593
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7960 - loss: 0.5619 - val_accuracy: 0.7941 - val_loss: 0.5500
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7960 - loss: 0.5541 - val_accuracy: 0.7941 - val_loss: 0.5406
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7960 - loss: 0.5460 - val_accuracy: 0.7941 - val_loss: 0.5315
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7960 - loss: 0.5373 - val_accuracy: 0.7941 - val_loss: 0.5234
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7960 - loss: 0.5300 - val_accuracy: 0.7941 - val_loss: 0.5148
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7960 - loss: 0.5221 - val_accuracy: 0.7941 - val_loss: 0.5061
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7960 - loss: 0.5143 - val_accuracy: 0.7941 - val_loss: 0.4980
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7960 - loss: 0.5065 - val_accuracy: 0.7941 - val_loss: 0.4897
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7960 - loss: 0.4993 - val_accuracy: 0.7941 - val_loss: 0.4806
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7960 - loss: 0.4912 - val_accuracy: 0.7941 - val_loss: 0.4733
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7960 - loss: 0.4840 - val_accuracy: 0.7941 - val_loss: 0.4649
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7960 - loss: 0.4767 - val_accuracy: 0.7941 - val_loss: 0.4565
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7960 - loss: 0.4694 - val_accuracy: 0.7941 - val_loss: 0.4483
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7960 - loss: 0.4622 - val_accuracy: 0.7941 - val_loss: 0.4404
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7960 - loss: 0.4548 - val_accuracy: 0.7941 - val_loss: 0.4330
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7960 - loss: 0.4479 - val_accuracy: 0.7941 - val_loss: 0.4260
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7960 - loss: 0.4412 - val_accuracy: 0.7941 - val_loss: 0.4167
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7960 - loss: 0.4344 - val_accuracy: 0.7941 - val_loss: 0.4094
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7960 - loss: 0.4282 - val_accuracy: 0.7941 - val_loss: 0.4024
11/11 - 0s - 7ms/step - accuracy: 0.7958 - loss: 0.4213

In [14]:
model_logit_true = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_true.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_true.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 100, validation_split = 0.1)

scores = model_logit_true.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.7960 - loss: 0.4184 - val_accuracy: 0.7941 - val_loss: 0.3869
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7960 - loss: 0.4084 - val_accuracy: 0.7941 - val_loss: 0.3780
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7960 - loss: 0.4001 - val_accuracy: 0.7941 - val_loss: 0.3709
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7960 - loss: 0.3939 - val_accuracy: 0.7941 - val_loss: 0.3642
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7960 - loss: 0.3882 - val_accuracy: 0.7941 - val_loss: 0.3577
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7960 - loss: 0.3823 - val_accuracy: 0.7941 - val_loss: 0.3512
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7960 - loss: 0.3764 - val_accuracy: 0.7941 - val_loss: 0.3447
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.3707 - val_accuracy: 0.7941 - val_loss: 0.3384
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.3650 - val_accuracy: 0.7941 - val_loss: 0.3319
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7960 - loss: 0.3592 - val_accuracy: 0.7941 - val_loss: 0.3251
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.3534 - val_accuracy: 0.7941 - val_loss: 0.3192
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.3480 - val_accuracy: 0.7941 - val_loss: 0.3122
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7960 - loss: 0.3426 - val_accuracy: 0.7941 - val_loss: 0.3066
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8094 - loss: 0.3375 - val_accuracy: 0.7941 - val_loss: 0.3008
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8094 - loss: 0.3323 - val_accuracy: 0.7941 - val_loss: 0.2949
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8161 - loss: 0.3274 - val_accuracy: 0.8529 - val_loss: 0.2891
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8161 - loss: 0.3224 - val_accuracy: 0.8529 - val_loss: 0.2839
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8261 - loss: 0.3174 - val_accuracy: 0.8529 - val_loss: 0.2779
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8294 - loss: 0.3123 - val_accuracy: 0.8824 - val_loss: 0.2721
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8395 - loss: 0.3079 - val_accuracy: 0.9118 - val_loss: 0.2664
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8495 - loss: 0.3023 - val_accuracy: 0.9118 - val_loss: 0.2604
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8528 - loss: 0.2980 - val_accuracy: 0.9118 - val_loss: 0.2552
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8662 - loss: 0.2932 - val_accuracy: 0.9412 - val_loss: 0.2497
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8796 - loss: 0.2890 - val_accuracy: 0.9412 - val_loss: 0.2444
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8863 - loss: 0.2839 - val_accuracy: 0.9412 - val_loss: 0.2385
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8863 - loss: 0.2807 - val_accuracy: 0.9412 - val_loss: 0.2338
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8896 - loss: 0.2765 - val_accuracy: 0.9412 - val_loss: 0.2295
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8997 - loss: 0.2719 - val_accuracy: 0.9706 - val_loss: 0.2244
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9064 - loss: 0.2677 - val_accuracy: 0.9706 - val_loss: 0.2193
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9097 - loss: 0.2656 - val_accuracy: 0.9706 - val_loss: 0.2144
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9097 - loss: 0.2599 - val_accuracy: 0.9706 - val_loss: 0.2102
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9164 - loss: 0.2565 - val_accuracy: 0.9706 - val_loss: 0.2057
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9164 - loss: 0.2527 - val_accuracy: 0.9706 - val_loss: 0.2010
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9197 - loss: 0.2487 - val_accuracy: 0.9706 - val_loss: 0.1962
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9231 - loss: 0.2449 - val_accuracy: 0.9706 - val_loss: 0.1918
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9197 - loss: 0.2414 - val_accuracy: 0.9706 - val_loss: 0.1878
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9197 - loss: 0.2386 - val_accuracy: 0.9706 - val_loss: 0.1833
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9264 - loss: 0.2346 - val_accuracy: 0.9706 - val_loss: 0.1793
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9365 - loss: 0.2322 - val_accuracy: 0.9706 - val_loss: 0.1760
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9264 - loss: 0.2278 - val_accuracy: 0.9706 - val_loss: 0.1719
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9398 - loss: 0.2252 - val_accuracy: 0.9706 - val_loss: 0.1679
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9398 - loss: 0.2210 - val_accuracy: 0.9706 - val_loss: 0.1642
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9365 - loss: 0.2188 - val_accuracy: 0.9706 - val_loss: 0.1606
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9365 - loss: 0.2156 - val_accuracy: 1.0000 - val_loss: 0.1566
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9365 - loss: 0.2117 - val_accuracy: 1.0000 - val_loss: 0.1526
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.9465 - loss: 0.2091 - val_accuracy: 1.0000 - val_loss: 0.1488
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9465 - loss: 0.2054 - val_accuracy: 1.0000 - val_loss: 0.1449
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9498 - loss: 0.2027 - val_accuracy: 1.0000 - val_loss: 0.1422
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9498 - loss: 0.1991 - val_accuracy: 1.0000 - val_loss: 0.1379
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9498 - loss: 0.1964 - val_accuracy: 1.0000 - val_loss: 0.1348
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.9498 - loss: 0.1932 - val_accuracy: 1.0000 - val_loss: 0.1314
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9498 - loss: 0.1912 - val_accuracy: 1.0000 - val_loss: 0.1300
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9431 - loss: 0.1898 - val_accuracy: 1.0000 - val_loss: 0.1261
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9431 - loss: 0.1859 - val_accuracy: 1.0000 - val_loss: 0.1234
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9498 - loss: 0.1845 - val_accuracy: 1.0000 - val_loss: 0.1206
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9498 - loss: 0.1812 - val_accuracy: 1.0000 - val_loss: 0.1179
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9465 - loss: 0.1795 - val_accuracy: 1.0000 - val_loss: 0.1155
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9498 - loss: 0.1768 - val_accuracy: 1.0000 - val_loss: 0.1130
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9498 - loss: 0.1745 - val_accuracy: 1.0000 - val_loss: 0.1103
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.9465 - loss: 0.1724 - val_accuracy: 1.0000 - val_loss: 0.1078
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9532 - loss: 0.1703 - val_accuracy: 1.0000 - val_loss: 0.1050
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9498 - loss: 0.1688 - val_accuracy: 1.0000 - val_loss: 0.1027
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9498 - loss: 0.1657 - val_accuracy: 1.0000 - val_loss: 0.1004
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.9465 - loss: 0.1646 - val_accuracy: 1.0000 - val_loss: 0.0981
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9498 - loss: 0.1620 - val_accuracy: 1.0000 - val_loss: 0.0959
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.9532 - loss: 0.1599 - val_accuracy: 1.0000 - val_loss: 0.0938
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9565 - loss: 0.1574 - val_accuracy: 1.0000 - val_loss: 0.0917
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9498 - loss: 0.1561 - val_accuracy: 1.0000 - val_loss: 0.0907
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9465 - loss: 0.1543 - val_accuracy: 1.0000 - val_loss: 0.0874
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9532 - loss: 0.1518 - val_accuracy: 1.0000 - val_loss: 0.0857
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.9498 - loss: 0.1507 - val_accuracy: 1.0000 - val_loss: 0.0837
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.9532 - loss: 0.1488 - val_accuracy: 1.0000 - val_loss: 0.0828
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.9498 - loss: 0.1473 - val_accuracy: 1.0000 - val_loss: 0.0802
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9532 - loss: 0.1451 - val_accuracy: 1.0000 - val_loss: 0.0783
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 160ms/step - accuracy: 0.9565 - loss: 0.1435 - val_accuracy: 1.0000 - val_loss: 0.0764
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 125ms/step - accuracy: 0.9565 - loss: 0.1428 - val_accuracy: 1.0000 - val_loss: 0.0750
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9532 - loss: 0.1412 - val_accuracy: 1.0000 - val_loss: 0.0736
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.9532 - loss: 0.1389 - val_accuracy: 1.0000 - val_loss: 0.0719
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9532 - loss: 0.1376 - val_accuracy: 1.0000 - val_loss: 0.0707
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9565 - loss: 0.1357 - val_accuracy: 1.0000 - val_loss: 0.0688
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 119ms/step - accuracy: 0.9532 - loss: 0.1345 - val_accuracy: 1.0000 - val_loss: 0.0676
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - accuracy: 0.9565 - loss: 0.1334 - val_accuracy: 1.0000 - val_loss: 0.0660
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9565 - loss: 0.1336 - val_accuracy: 1.0000 - val_loss: 0.0653
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 77ms/step - accuracy: 0.9532 - loss: 0.1305 - val_accuracy: 1.0000 - val_loss: 0.0638
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9565 - loss: 0.1296 - val_accuracy: 1.0000 - val_loss: 0.0627
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9565 - loss: 0.1281 - val_accuracy: 1.0000 - val_loss: 0.0614
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.9532 - loss: 0.1277 - val_accuracy: 1.0000 - val_loss: 0.0603
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9532 - loss: 0.1259 - val_accuracy: 1.0000 - val_loss: 0.0589
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9532 - loss: 0.1251 - val_accuracy: 1.0000 - val_loss: 0.0583
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9532 - loss: 0.1245 - val_accuracy: 1.0000 - val_loss: 0.0575
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9565 - loss: 0.1242 - val_accuracy: 1.0000 - val_loss: 0.0560
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.9565 - loss: 0.1217 - val_accuracy: 1.0000 - val_loss: 0.0548
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.9532 - loss: 0.1218 - val_accuracy: 1.0000 - val_loss: 0.0537
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9532 - loss: 0.1196 - val_accuracy: 1.0000 - val_loss: 0.0528
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.9565 - loss: 0.1190 - val_accuracy: 1.0000 - val_loss: 0.0518
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9532 - loss: 0.1180 - val_accuracy: 1.0000 - val_loss: 0.0509
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9532 - loss: 0.1179 - val_accuracy: 1.0000 - val_loss: 0.0499
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9532 - loss: 0.1171 - val_accuracy: 1.0000 - val_loss: 0.0493
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9565 - loss: 0.1154 - val_accuracy: 1.0000 - val_loss: 0.0484
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.9532 - loss: 0.1141 - val_accuracy: 1.0000 - val_loss: 0.0475
11/11 - 0s - 13ms/step - accuracy: 0.9640 - loss: 0.1066

In [15]:
model_logit_true.predict(scaled_penguins_x)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

array([[9.96885538e-01, 9.44543362e-01, 1.24828899e-02],
       [1.21970914e-01, 8.23972464e-01, 5.87416530e-01],
       [9.96758878e-01, 9.57440257e-01, 1.17469709e-02],
       [8.63278692e-04, 2.39080161e-01, 9.70543265e-01],
       [9.96541619e-01, 9.50634778e-01, 1.28137432e-02],
       [5.25843501e-01, 9.43404853e-01, 2.68571556e-01],
       [9.12683725e-01, 9.56843436e-01, 8.67891237e-02],
       [3.38708889e-03, 3.64645094e-01, 9.37117338e-01],
       [6.60610618e-04, 2.29315028e-01, 9.73994136e-01],
       [2.45210063e-03, 3.09064060e-01, 9.49533999e-01],
       [9.11611736e-01, 9.45889473e-01, 9.34874043e-02],
       [9.99970436e-01, 9.75064933e-01, 5.60162938e-04],
       [9.65310335e-01, 9.49100673e-01, 5.21257818e-02],
       [9.99444604e-01, 9.63499367e-01, 3.81322042e-03],
       [6.66734517e-01, 9.51605082e-01, 2.13578537e-01],
       [9.96514499e-01, 9.47754383e-01, 1.31116714e-02],
       [9.99496579e-01, 9.53130901e-01, 3.89119121e-03],
       [9.60380363e-04, 2.43049383e-01, 9.69047964e-01],
       [9.99691725e-01, 9.65273321e-01, 2.61812960e-03],
       [4.73903060e-01, 9.28995013e-01, 3.06355566e-01],
       [9.90814328e-01, 9.49918032e-01, 2.32729595e-02],
       [9.95053411e-01, 9.38492715e-01, 1.70918442e-02],
       [1.11786664e-01, 7.92592764e-01, 6.17368460e-01],
       [6.18563383e-04, 2.26958573e-01, 9.74780083e-01],
       [9.98436213e-01, 9.55860853e-01, 7.62510579e-03],
       [9.98162806e-01, 9.48530614e-01, 8.83861911e-03],
       [6.60397520e-04, 2.29303405e-01, 9.73998070e-01],
       [6.72995329e-01, 9.46699262e-01, 2.16177449e-01],
       [4.98085399e-04, 2.19318494e-01, 9.77208436e-01],
       [8.80068541e-01, 9.57377613e-01, 1.05221875e-01],
       [1.31635228e-03, 2.55052418e-01, 9.64181483e-01],
       [4.31647599e-01, 9.26674783e-01, 3.23974818e-01],
       [9.96486485e-01, 9.60286081e-01, 1.20687401e-02],
       [9.97599602e-01, 9.63034391e-01, 9.35511198e-03],
       [2.77509481e-01, 8.72942626e-01, 4.47992593e-01],
       [8.10704470e-01, 9.51609671e-01, 1.45656154e-01],
       [8.22275281e-02, 7.89300382e-01, 6.50236726e-01],
       [3.96631513e-04, 2.11487904e-01, 9.79514897e-01],
       [9.99734104e-01, 9.60535288e-01, 2.49155308e-03],
       [9.98649120e-01, 9.43033278e-01, 7.57351657e-03],
       [9.99960482e-01, 9.64616001e-01, 7.37818074e-04],
       [9.99505579e-01, 9.59793210e-01, 3.66332754e-03],
       [1.44329481e-03, 2.58630782e-01, 9.62626159e-01],
       [1.21881836e-03, 2.52085686e-01, 9.65433836e-01],
       [9.98740017e-01, 9.53802168e-01, 6.78263931e-03],
       [9.92413104e-01, 9.46471572e-01, 2.11756974e-02],
       [7.93709278e-01, 9.55283701e-01, 1.50720865e-01],
       [9.98771489e-01, 9.57759798e-01, 6.48944359e-03],
       [9.99858201e-01, 9.66975749e-01, 1.60141627e-03],
       [6.29260123e-01, 9.51627135e-01, 2.24566668e-01],
       [9.99290347e-01, 9.61870372e-01, 4.49178135e-03],
       [1.15424581e-03, 2.69943148e-01, 9.64825392e-01],
       [9.80021898e-04, 2.43808359e-01, 9.68755722e-01],
       [9.99841988e-01, 9.57934260e-01, 1.84917473e-03],
       [9.99775469e-01, 9.73533690e-01, 1.97771029e-03],
       [7.48758391e-03, 4.63109821e-01, 9.01629448e-01],
       [9.96781170e-01, 9.50911939e-01, 1.22446595e-02],
       [9.99379277e-01, 9.71582532e-01, 3.76896258e-03],
       [6.58158446e-04, 2.29181319e-01, 9.74039257e-01],
       [3.33322329e-04, 2.05648810e-01, 9.81120408e-01],
       [9.16927159e-01, 9.44188058e-01, 9.08534154e-02],
       [5.72131395e-01, 9.37046766e-01, 2.63668299e-01],
       [7.62468219e-01, 9.53697681e-01, 1.67069986e-01],
       [9.99866128e-01, 9.67708647e-01, 1.53513299e-03],
       [9.99922931e-01, 9.65223610e-01, 1.12055184e-03],
       [3.70275080e-01, 9.06549990e-01, 3.72240275e-01],
       [9.92338717e-01, 9.48836207e-01, 2.09959373e-02],
       [6.85735722e-04, 2.30660200e-01, 9.73537505e-01],
       [9.98851418e-01, 9.57962275e-01, 6.21871604e-03],
       [9.74025011e-01, 9.44207013e-01, 4.50643189e-02],
       [9.99866247e-01, 9.68157709e-01, 1.52727414e-03],
       [9.99139726e-01, 9.57160532e-01, 5.24442410e-03],
       [6.66099368e-04, 2.29612708e-01, 9.73893583e-01],
       [5.35883605e-01, 9.36524451e-01, 2.75737733e-01],
       [1.34242838e-03, 2.62575150e-01, 9.63329136e-01],
       [1.24868145e-03, 2.53016025e-01, 9.65044677e-01],
       [9.99721527e-01, 9.61464167e-01, 2.54347501e-03],
       [9.99924719e-01, 9.70555007e-01, 1.04727782e-03],
       [9.99517977e-01, 9.52966869e-01, 3.79357999e-03],
       [4.32923390e-03, 3.66946697e-01, 9.30909574e-01],
       [9.96173203e-01, 9.46857750e-01, 1.39532760e-02],
       [9.99032676e-01, 9.56137180e-01, 5.67675428e-03],
       [3.49040469e-03, 3.56092155e-01, 9.37351823e-01],
       [9.98826802e-01, 9.63370740e-01, 6.02824055e-03],
       [7.47481704e-01, 9.43337262e-01, 1.83769152e-01],
       [2.68974982e-04, 1.98612809e-01, 9.82931316e-01],
       [9.99793530e-01, 9.66562390e-01, 2.02367920e-03],
       [8.33662674e-02, 7.80009091e-01, 6.54216170e-01],
       [8.87840521e-03, 4.47005898e-01, 8.98054361e-01],
       [8.53390316e-04, 2.38653839e-01, 9.70700622e-01],
       [5.71230135e-04, 2.24129185e-01, 9.75700498e-01],
       [7.52249300e-01, 9.40678775e-01, 1.83687881e-01],
       [9.94591713e-01, 9.53274190e-01, 1.65169407e-02],
       [9.95096445e-01, 9.48134661e-01, 1.60925351e-02],
       [9.98242557e-01, 9.58032250e-01, 8.05628486e-03],
       [9.99903977e-01, 9.58173990e-01, 1.36078557e-03],
       [9.99236643e-01, 9.63937879e-01, 4.61359276e-03],
       [7.24323210e-04, 2.32643098e-01, 9.72853601e-01],
       [9.90820467e-01, 9.51230586e-01, 2.30681282e-02],
       [9.99837399e-01, 9.72779810e-01, 1.63771887e-03],
       [9.97201979e-01, 9.54667270e-01, 1.09612560e-02],
       [5.88289201e-01, 9.35332775e-01, 2.61000663e-01],
       [3.82709235e-01, 9.19714868e-01, 3.51103812e-01],
       [9.96095002e-01, 9.51978207e-01, 1.36734927e-02],
       [1.94182619e-03, 2.78177738e-01, 9.56469655e-01],
       [9.99207020e-01, 9.58738983e-01, 4.93023405e-03],
       [6.90736633e-04, 2.30922714e-01, 9.73447740e-01],
       [1.08536240e-03, 2.47660413e-01, 9.67240870e-01],
       [9.99709249e-01, 9.63347912e-01, 2.57009314e-03],
       [3.72061622e-03, 3.50545824e-01, 9.36477780e-01],
       [9.99322712e-01, 9.49042261e-01, 4.79276478e-03],
       [3.32265377e-01, 8.96110296e-01, 3.99594665e-01],
       [8.88901174e-01, 9.51577425e-01, 1.04123414e-01],
       [6.43756241e-03, 4.17214215e-01, 9.13289964e-01],
       [6.41946099e-04, 2.28285968e-01, 9.74339545e-01],
       [8.78936320e-04, 2.39746332e-01, 9.70296144e-01],
       [9.98308480e-01, 9.57390070e-01, 7.90914334e-03],
       [1.03476644e-03, 2.45854110e-01, 9.67957854e-01],
       [9.61196423e-01, 9.53770101e-01, 5.41427061e-02],
       [8.08781537e-04, 2.36674130e-01, 9.71423209e-01],
       [9.99470294e-01, 9.52610970e-01, 4.02867235e-03],
       [1.07702136e-03, 2.47367889e-01, 9.67357814e-01],
       [7.37576544e-01, 9.48909044e-01, 1.83462918e-01],
       [9.99591887e-01, 9.56802726e-01, 3.33367474e-03],
       [9.98911858e-01, 9.43029583e-01, 6.63786056e-03],
       [2.06925780e-01, 8.69108558e-01, 4.89333659e-01],
       [9.99901354e-01, 9.39739645e-01, 1.44350983e-03],
       [9.99448836e-01, 9.66527283e-01, 3.69196711e-03],
       [9.90731955e-01, 9.51755285e-01, 2.31228676e-02],
       [3.18057486e-04, 2.04095423e-01, 9.81531620e-01],
       [9.96169329e-01, 9.40633655e-01, 1.44703696e-02],
       [9.99848843e-01, 9.67398345e-01, 1.65854185e-03],
       [1.03684945e-03, 2.45930046e-01, 9.67927933e-01],
       [9.98726845e-01, 9.58576560e-01, 6.59081666e-03],
       [9.99951720e-01, 9.57490087e-01, 8.58440297e-04],
       [9.99949098e-01, 9.60717976e-01, 8.85436952e-04],
       [8.36638967e-04, 2.37921506e-01, 9.70969498e-01],
       [9.64924693e-01, 9.52249706e-01, 5.14507778e-02],
       [8.42155576e-01, 9.53197360e-01, 1.28451869e-01],
       [9.97881114e-01, 9.54915464e-01, 9.23834369e-03],
       [9.96258557e-01, 9.57091510e-01, 1.28518064e-02],
       [6.67685119e-04, 2.29698330e-01, 9.73864675e-01],
       [9.99784410e-01, 9.54940796e-01, 2.28687585e-03],
       [2.15031821e-02, 6.02573395e-01, 8.25801969e-01],
       [1.26567332e-03, 2.53536493e-01, 9.64825571e-01],
       [9.03500676e-01, 9.56246614e-01, 9.26664621e-02],
       [8.53945909e-04, 2.38677919e-01, 9.70691741e-01],
       [2.44215026e-01, 8.85428190e-01, 4.52362061e-01],
       [8.97820457e-04, 2.40535840e-01, 9.70001221e-01],
       [8.29550321e-04, 2.37607658e-01, 9.71084118e-01],
       [2.34153681e-03, 3.13387930e-01, 9.49989021e-01],
       [6.84453640e-04, 2.30592623e-01, 9.73560572e-01],
       [9.95139360e-01, 9.43598449e-01, 1.64443888e-02],
       [9.91069674e-01, 9.60540473e-01, 2.12168824e-02],
       [9.54722229e-04, 2.42828175e-01, 9.69132721e-01],
       [7.06990482e-03, 4.47334379e-01, 9.05955315e-01],
       [1.16217684e-03, 2.50263393e-01, 9.66186762e-01],
       [9.98893797e-01, 9.53390718e-01, 6.28290139e-03],
       [5.88716054e-03, 4.00411308e-01, 9.18290734e-01],
       [1.55234626e-02, 5.52846849e-01, 8.54850590e-01],
       [9.95279193e-01, 9.53287840e-01, 1.52077405e-02],
       [7.32272863e-01, 9.54469800e-01, 1.80376723e-01],
       [5.89888811e-01, 9.34044659e-01, 2.62236327e-01],
       [4.30484504e-01, 9.35237646e-01, 3.12058926e-01],
       [1.15917949e-03, 2.50164777e-01, 9.66227114e-01],
       [4.32780990e-03, 4.20410901e-01, 9.24517274e-01],
       [8.70101212e-04, 2.39371747e-01, 9.70435262e-01],
       [2.04587285e-03, 2.72490293e-01, 9.56120253e-01],
       [8.16507731e-04, 2.37023860e-01, 9.71296489e-01],
       [9.92721498e-01, 9.57279325e-01, 1.92201864e-02],
       [9.99879241e-01, 9.65942442e-01, 1.46581221e-03],
       [8.38914886e-04, 2.38021791e-01, 9.70932782e-01],
       [5.38293898e-01, 9.25009608e-01, 2.90442586e-01],
       [9.96734798e-01, 9.55103636e-01, 1.20032504e-02],
       [5.24181604e-01, 9.31943297e-01, 2.85871327e-01],
       [6.61930084e-01, 9.50770319e-01, 2.16295660e-01],
       [9.99125302e-01, 9.57483053e-01, 5.28521370e-03],
       [9.99720097e-01, 9.55107272e-01, 2.68001971e-03],
       [9.96324420e-01, 9.53915596e-01, 1.30070522e-02],
       [9.98903811e-01, 9.63626683e-01, 5.77061763e-03],
       [5.30672193e-01, 9.30372775e-01, 2.85917819e-01],
       [9.96603072e-01, 9.60607290e-01, 1.17931105e-02],
       [2.17201677e-03, 2.77492762e-01, 9.54663396e-01],
       [5.30747831e-01, 9.30386424e-01, 2.85875201e-01],
       [9.97559905e-01, 9.49436903e-01, 1.04454318e-02],
       [5.36457868e-03, 3.93777370e-01, 9.21852708e-01],
       [6.37665391e-04, 2.28046194e-01, 9.74419534e-01],
       [9.95916247e-01, 9.55068052e-01, 1.37547087e-02],
       [7.59863257e-01, 9.48348343e-01, 1.73330888e-01],
       [9.98881280e-01, 9.53766108e-01, 6.30962104e-03],
       [8.18263054e-01, 9.49100852e-01, 1.43892795e-01],
       [9.81946409e-01, 9.51678991e-01, 3.46041322e-02],
       [8.12689075e-04, 2.36851379e-01, 9.71359015e-01],
       [8.90553772e-01, 9.49209869e-01, 1.04609318e-01],
       [1.02555775e-03, 2.45516866e-01, 9.68090415e-01],
       [9.98076916e-01, 9.68550265e-01, 7.76419509e-03],
       [9.99911666e-01, 9.57430661e-01, 1.29989919e-03],
       [9.98805583e-01, 9.56793725e-01, 6.42531598e-03],
       [8.11005710e-04, 2.36775145e-01, 9.71386671e-01],
       [9.98845935e-01, 9.60062563e-01, 6.13526255e-03],
       [4.94481123e-04, 2.19065607e-01, 9.77285743e-01],
       [9.99385834e-01, 9.66249883e-01, 3.95486411e-03],
       [9.56766546e-01, 9.57629681e-01, 5.62778637e-02],
       [9.98603046e-01, 9.56265390e-01, 7.09727500e-03],
       [9.97467458e-01, 9.65542972e-01, 9.45220888e-03],
       [4.94340260e-04, 2.19055697e-01, 9.77288783e-01],
       [1.54724126e-04, 1.81315407e-01, 9.86848593e-01],
       [6.96948904e-04, 2.31246442e-01, 9.73336637e-01],
       [8.86427999e-01, 9.47857857e-01, 1.07847668e-01],
       [9.99221206e-01, 9.57166910e-01, 4.93495446e-03],
       [9.92780507e-01, 9.58271384e-01, 1.89837907e-02],
       [5.55012841e-04, 2.23111778e-01, 9.76025283e-01],
       [2.03750376e-03, 2.76954591e-01, 9.55786288e-01],
       [9.99325633e-01, 9.42759752e-01, 4.96455096e-03],
       [9.99774694e-01, 9.53533769e-01, 2.37316918e-03],
       [2.71244496e-01, 8.73076916e-01, 4.50917125e-01],
       [9.99846041e-01, 9.61457491e-01, 1.76950858e-03],
       [3.81159654e-04, 2.10141197e-01, 9.79893684e-01],
       [9.99595404e-01, 9.56732094e-01, 3.31798405e-03],
       [8.07313800e-01, 9.44731653e-01, 1.52867243e-01],
       [8.27364802e-01, 9.33695614e-01, 1.49973184e-01],
       [6.23493791e-01, 9.34964597e-01, 2.50488967e-01],
       [9.47915375e-01, 9.56035614e-01, 6.37062639e-02],
       [8.85780377e-04, 2.40034238e-01, 9.70188856e-01],
       [9.50992465e-01, 9.40203369e-01, 6.74383938e-02],
       [1.01730390e-03, 2.45212302e-01, 9.68209803e-01],
       [6.67278655e-04, 2.29676411e-01, 9.73872066e-01],
       [9.81548548e-01, 9.56654906e-01, 3.38899307e-02],
       [6.86872890e-03, 4.18518096e-01, 9.11057830e-01],
       [9.99783933e-01, 9.61308718e-01, 2.18042871e-03],
       [9.97521996e-01, 9.52703118e-01, 1.03197638e-02],
       [5.79135912e-03, 4.48174059e-01, 9.12333608e-01],
       [9.98438597e-01, 9.58347261e-01, 7.47775612e-03],
       [1.60355016e-03, 2.62763768e-01, 9.60767508e-01],
       [9.97178972e-01, 9.60691810e-01, 1.05255507e-02],
       [6.89311244e-04, 2.30848074e-01, 9.73473251e-01],
       [8.67291987e-02, 7.85115480e-01, 6.47461832e-01],
       [9.99029994e-01, 9.65174258e-01, 5.28163230e-03],
       [8.49135935e-01, 9.57324684e-01, 1.21595554e-01],
       [1.04759308e-02, 4.89608973e-01, 8.84667099e-01],
       [4.96452212e-01, 9.26092982e-01, 3.02755296e-01],
       [9.97394383e-01, 9.55417216e-01, 1.04403077e-02],
       [6.96021307e-04, 2.31198311e-01, 9.73353207e-01],
       [1.65975268e-03, 2.79906452e-01, 9.58820581e-01],
       [6.79879216e-04, 2.30350643e-01, 9.73643124e-01],
       [9.99865472e-01, 9.69757915e-01, 1.50777027e-03],
       [9.95516360e-01, 9.50300515e-01, 1.50346113e-02],
       [9.97044325e-01, 9.57422137e-01, 1.11079197e-02],
       [8.99743196e-03, 4.96183127e-01, 8.89574885e-01],
       [5.55988494e-03, 3.88645262e-01, 9.21497822e-01],
       [6.16508361e-04, 2.26839781e-01, 9.74819243e-01],
       [9.72897410e-01, 9.49012518e-01, 4.49507311e-02],
       [1.18975481e-03, 2.51160353e-01, 9.65817690e-01],
       [9.97489214e-01, 9.49546278e-01, 1.06210485e-02],
       [9.98764157e-01, 9.49077249e-01, 6.91716559e-03],
       [7.00360630e-03, 4.37595874e-01, 9.07690167e-01],
       [9.97066021e-01, 9.40661013e-01, 1.23049989e-02],
       [9.98215139e-01, 9.55507815e-01, 8.28637369e-03],
       [9.99932647e-01, 9.73513186e-01, 9.46025131e-04],
       [9.99962986e-01, 9.67901528e-01, 6.96634175e-04],
       [9.94883299e-01, 9.70766723e-01, 1.37682538e-02],
       [3.10869957e-03, 3.38046283e-01, 9.41859305e-01],
       [9.98618901e-01, 9.57577884e-01, 6.97939610e-03],
       [6.45065665e-01, 9.46813881e-01, 2.27322668e-01],
       [9.81742203e-01, 9.50280666e-01, 3.51528823e-02],
       [2.63497792e-03, 3.13396424e-01, 9.47737455e-01],
       [5.31776905e-01, 9.31036949e-01, 2.84668922e-01],
       [1.19134621e-03, 2.51211554e-01, 9.65796530e-01],
       [1.16982381e-03, 2.50514001e-01, 9.66083944e-01],
       [1.08264445e-03, 2.47565299e-01, 9.67278898e-01],
       [3.07618737e-01, 9.03666377e-01, 4.01679188e-01],
       [3.08917789e-03, 3.31988186e-01, 9.42624390e-01],
       [9.61530447e-01, 9.62871969e-01, 5.03680296e-02],
       [7.65293539e-01, 9.55142379e-01, 1.64322063e-01],
       [6.37889504e-01, 9.49401319e-01, 2.25540966e-01],
       [3.63424071e-03, 3.42623085e-01, 9.37898815e-01],
       [1.02104875e-03, 2.45350763e-01, 9.68155563e-01],
       [9.99293447e-01, 9.71403062e-01, 4.08756267e-03],
       [5.30722959e-04, 2.21537516e-01, 9.76521671e-01],
       [9.12827265e-04, 2.41152763e-01, 9.69769299e-01],
       [8.91711912e-04, 2.40282103e-01, 9.70096231e-01],
       [9.87290740e-01, 9.63694453e-01, 2.55935863e-02],
       [9.99792576e-01, 9.61254239e-01, 2.12744600e-03],
       [9.86976206e-01, 9.54298079e-01, 2.79199649e-02],
       [9.97822225e-01, 9.53724742e-01, 9.47287213e-03],
       [9.99928057e-01, 9.65014040e-01, 1.07659854e-03],
       [2.06037052e-03, 2.72775620e-01, 9.55977976e-01],
       [9.98974025e-01, 9.59734440e-01, 5.72511740e-03],
       [8.99021048e-04, 2.40585551e-01, 9.69982624e-01],
       [9.97304857e-01, 9.54389036e-01, 1.07351784e-02],
       [9.99691725e-01, 9.45445359e-01, 3.02859093e-03],
       [2.76208972e-03, 3.25053304e-01, 9.45650339e-01],
       [4.93661442e-04, 2.19007850e-01, 9.77303386e-01],
       [9.99965072e-01, 9.60509896e-01, 6.82508107e-04],
       [9.99366462e-01, 9.54482734e-01, 4.43637324e-03],
       [6.38122678e-01, 9.56576824e-01, 2.13761702e-01],
       [6.93238981e-04, 2.31053442e-01, 9.73402917e-01],
       [3.71265709e-01, 9.05921936e-01, 3.72586995e-01],
       [9.70227838e-01, 9.51225221e-01, 4.69169281e-02],
       [5.86446047e-01, 9.35875177e-01, 2.60836095e-01],
       [1.14259101e-03, 2.49614686e-01, 9.66451764e-01],
       [9.99556005e-01, 9.50927615e-01, 3.65770143e-03],
       [9.95647550e-01, 9.54377294e-01, 1.43672219e-02],
       [8.81283195e-04, 2.39845261e-01, 9.70259309e-01],
       [8.95407866e-04, 2.40435824e-01, 9.70038712e-01],
       [4.04454678e-01, 9.15474713e-01, 3.48412961e-01],
       [1.61240541e-03, 2.62981117e-01, 9.60667849e-01],
       [1.49687817e-02, 5.39893508e-01, 8.59350502e-01],
       [9.99796629e-01, 9.50236678e-01, 2.27869046e-03],
       [9.99964476e-01, 9.56394672e-01, 6.94966817e-04],
       [8.71630560e-04, 2.39436850e-01, 9.70411122e-01],
       [2.47581978e-03, 2.91779220e-01, 9.51010704e-01],
       [9.99079227e-01, 9.54370439e-01, 5.57886902e-03],
       [3.22579290e-03, 3.40616077e-01, 9.40786660e-01],
       [8.20036769e-01, 9.58195150e-01, 1.35347396e-01],
       [1.84550218e-03, 2.68346965e-01, 9.58147705e-01],
       [5.89497447e-01, 9.42950487e-01, 2.49821529e-01],
       [9.95575101e-04, 2.44399771e-01, 9.68526602e-01],
       [4.34263051e-01, 9.16684210e-01, 3.36100012e-01],
       [8.29232333e-04, 2.37593532e-01, 9.71089303e-01],
       [9.99594092e-01, 9.56631601e-01, 3.32700997e-03],
       [9.59109864e-04, 2.42999807e-01, 9.69066978e-01],
       [9.99540746e-01, 9.57720041e-01, 3.55870067e-03],
       [9.98194158e-01, 9.51464653e-01, 8.58234800e-03],
       [7.47713726e-04, 2.33799756e-01, 9.72448707e-01],
       [9.94318306e-01, 9.51372802e-01, 1.72364749e-02],
       [2.41972432e-01, 8.90644491e-01, 4.48013186e-01],
       [9.99889135e-01, 9.66698587e-01, 1.38106081e-03],
       [2.36467901e-03, 2.78380334e-01, 9.53112066e-01],
       [9.99896646e-01, 9.63724554e-01, 1.35960919e-03],
       [9.94681597e-01, 9.55138683e-01, 1.61390956e-02],
       [4.39306259e-01, 9.27244008e-01, 3.20525736e-01],
       [9.98968124e-01, 9.48711097e-01, 6.21086825e-03]], dtype=float32)

In [16]:
penguins['species']

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: str

In [17]:
penguins_y

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0,
       0, 1, 0], dtype=int8)

In [18]:
# now do the same for logit false, name model "model_logit_false"
model_logit_false = keras.Model(inputs=inputs, outputs=outputs, name="model_logit_false")
model_logit_false.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)
history_logit_false = model_logit_false.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 100, validation_split = 0.1)
scores = model_logit_false.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

Epoch 1/100

c:\Users\ivpri\gsb545\.venv_clean\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9565 - loss: 0.1141 - val_accuracy: 1.0000 - val_loss: 0.0444
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9565 - loss: 0.1114 - val_accuracy: 1.0000 - val_loss: 0.0435
Epoch 3/100
1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9688 - loss: 0.0990

c:\Users\ivpri\gsb545\.venv_clean\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9532 - loss: 0.1108 - val_accuracy: 1.0000 - val_loss: 0.0428
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9565 - loss: 0.1100 - val_accuracy: 1.0000 - val_loss: 0.0421
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9565 - loss: 0.1079 - val_accuracy: 1.0000 - val_loss: 0.0418
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9565 - loss: 0.1085 - val_accuracy: 1.0000 - val_loss: 0.0411
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9532 - loss: 0.1062 - val_accuracy: 1.0000 - val_loss: 0.0406
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9565 - loss: 0.1075 - val_accuracy: 1.0000 - val_loss: 0.0401
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9565 - loss: 0.1044 - val_accuracy: 1.0000 - val_loss: 0.0396
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9599 - loss: 0.1050 - val_accuracy: 1.0000 - val_loss: 0.0397
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9565 - loss: 0.1050 - val_accuracy: 1.0000 - val_loss: 0.0382
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9565 - loss: 0.1029 - val_accuracy: 1.0000 - val_loss: 0.0378
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9532 - loss: 0.1019 - val_accuracy: 1.0000 - val_loss: 0.0370
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9565 - loss: 0.1027 - val_accuracy: 1.0000 - val_loss: 0.0364
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.9599 - loss: 0.1009 - val_accuracy: 1.0000 - val_loss: 0.0357
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9532 - loss: 0.1033 - val_accuracy: 1.0000 - val_loss: 0.0351
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9632 - loss: 0.1010 - val_accuracy: 1.0000 - val_loss: 0.0348
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.9599 - loss: 0.0993 - val_accuracy: 1.0000 - val_loss: 0.0345
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9599 - loss: 0.0988 - val_accuracy: 1.0000 - val_loss: 0.0342
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 96ms/step - accuracy: 0.9599 - loss: 0.0983 - val_accuracy: 1.0000 - val_loss: 0.0332
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.9565 - loss: 0.0985 - val_accuracy: 1.0000 - val_loss: 0.0329
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9632 - loss: 0.0985 - val_accuracy: 1.0000 - val_loss: 0.0324
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.9532 - loss: 0.0967 - val_accuracy: 1.0000 - val_loss: 0.0320
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.9599 - loss: 0.0963 - val_accuracy: 1.0000 - val_loss: 0.0317
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9599 - loss: 0.0960 - val_accuracy: 1.0000 - val_loss: 0.0312
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9599 - loss: 0.0954 - val_accuracy: 1.0000 - val_loss: 0.0307
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9565 - loss: 0.0949 - val_accuracy: 1.0000 - val_loss: 0.0303
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.9632 - loss: 0.0960 - val_accuracy: 1.0000 - val_loss: 0.0299
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.9632 - loss: 0.0935 - val_accuracy: 1.0000 - val_loss: 0.0299
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.9599 - loss: 0.0933 - val_accuracy: 1.0000 - val_loss: 0.0297
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9599 - loss: 0.0930 - val_accuracy: 1.0000 - val_loss: 0.0293
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9599 - loss: 0.0921 - val_accuracy: 1.0000 - val_loss: 0.0284
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9599 - loss: 0.0928 - val_accuracy: 1.0000 - val_loss: 0.0282
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9599 - loss: 0.0911 - val_accuracy: 1.0000 - val_loss: 0.0279
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9632 - loss: 0.0910 - val_accuracy: 1.0000 - val_loss: 0.0278
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9565 - loss: 0.0910 - val_accuracy: 1.0000 - val_loss: 0.0272
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9632 - loss: 0.0902 - val_accuracy: 1.0000 - val_loss: 0.0268
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9632 - loss: 0.0900 - val_accuracy: 1.0000 - val_loss: 0.0265
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9599 - loss: 0.0899 - val_accuracy: 1.0000 - val_loss: 0.0261
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9632 - loss: 0.0900 - val_accuracy: 1.0000 - val_loss: 0.0255
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9632 - loss: 0.0882 - val_accuracy: 1.0000 - val_loss: 0.0254
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9632 - loss: 0.0882 - val_accuracy: 1.0000 - val_loss: 0.0249
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.9666 - loss: 0.0878 - val_accuracy: 1.0000 - val_loss: 0.0245
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9632 - loss: 0.0878 - val_accuracy: 1.0000 - val_loss: 0.0245
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.9632 - loss: 0.0880 - val_accuracy: 1.0000 - val_loss: 0.0241
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.9599 - loss: 0.0869 - val_accuracy: 1.0000 - val_loss: 0.0241
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.9632 - loss: 0.0881 - val_accuracy: 1.0000 - val_loss: 0.0237
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.9632 - loss: 0.0858 - val_accuracy: 1.0000 - val_loss: 0.0233
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9666 - loss: 0.0858 - val_accuracy: 1.0000 - val_loss: 0.0230
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9632 - loss: 0.0871 - val_accuracy: 1.0000 - val_loss: 0.0229
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9632 - loss: 0.0853 - val_accuracy: 1.0000 - val_loss: 0.0226
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9599 - loss: 0.0867 - val_accuracy: 1.0000 - val_loss: 0.0225
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 94ms/step - accuracy: 0.9632 - loss: 0.0851 - val_accuracy: 1.0000 - val_loss: 0.0228
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 138ms/step - accuracy: 0.9632 - loss: 0.0839 - val_accuracy: 1.0000 - val_loss: 0.0224
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 84ms/step - accuracy: 0.9666 - loss: 0.0848 - val_accuracy: 1.0000 - val_loss: 0.0222
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.9632 - loss: 0.0847 - val_accuracy: 1.0000 - val_loss: 0.0221
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9699 - loss: 0.0829 - val_accuracy: 1.0000 - val_loss: 0.0219
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.9666 - loss: 0.0837 - val_accuracy: 1.0000 - val_loss: 0.0215
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9632 - loss: 0.0834 - val_accuracy: 1.0000 - val_loss: 0.0211
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9632 - loss: 0.0838 - val_accuracy: 1.0000 - val_loss: 0.0210
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9666 - loss: 0.0820 - val_accuracy: 1.0000 - val_loss: 0.0211
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.9699 - loss: 0.0820 - val_accuracy: 1.0000 - val_loss: 0.0207
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9666 - loss: 0.0819 - val_accuracy: 1.0000 - val_loss: 0.0206
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 127ms/step - accuracy: 0.9632 - loss: 0.0825 - val_accuracy: 1.0000 - val_loss: 0.0206
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 131ms/step - accuracy: 0.9699 - loss: 0.0815 - val_accuracy: 1.0000 - val_loss: 0.0203
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 112ms/step - accuracy: 0.9699 - loss: 0.0809 - val_accuracy: 1.0000 - val_loss: 0.0201
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 112ms/step - accuracy: 0.9666 - loss: 0.0832 - val_accuracy: 1.0000 - val_loss: 0.0201
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.9666 - loss: 0.0800 - val_accuracy: 1.0000 - val_loss: 0.0201
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 101ms/step - accuracy: 0.9699 - loss: 0.0797 - val_accuracy: 1.0000 - val_loss: 0.0202
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.9699 - loss: 0.0812 - val_accuracy: 1.0000 - val_loss: 0.0199
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9666 - loss: 0.0812 - val_accuracy: 1.0000 - val_loss: 0.0198
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9632 - loss: 0.0808 - val_accuracy: 1.0000 - val_loss: 0.0195
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9666 - loss: 0.0805 - val_accuracy: 1.0000 - val_loss: 0.0193
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9699 - loss: 0.0791 - val_accuracy: 1.0000 - val_loss: 0.0191
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9699 - loss: 0.0782 - val_accuracy: 1.0000 - val_loss: 0.0186
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9666 - loss: 0.0794 - val_accuracy: 1.0000 - val_loss: 0.0188
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9666 - loss: 0.0793 - val_accuracy: 1.0000 - val_loss: 0.0181
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9666 - loss: 0.0784 - val_accuracy: 1.0000 - val_loss: 0.0182
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9699 - loss: 0.0778 - val_accuracy: 1.0000 - val_loss: 0.0179
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9699 - loss: 0.0788 - val_accuracy: 1.0000 - val_loss: 0.0180
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9699 - loss: 0.0768 - val_accuracy: 1.0000 - val_loss: 0.0180
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9699 - loss: 0.0767 - val_accuracy: 1.0000 - val_loss: 0.0175
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9632 - loss: 0.0786 - val_accuracy: 1.0000 - val_loss: 0.0176
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9666 - loss: 0.0768 - val_accuracy: 1.0000 - val_loss: 0.0175
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9699 - loss: 0.0761 - val_accuracy: 1.0000 - val_loss: 0.0170
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9699 - loss: 0.0767 - val_accuracy: 1.0000 - val_loss: 0.0171
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9699 - loss: 0.0771 - val_accuracy: 1.0000 - val_loss: 0.0172
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9699 - loss: 0.0775 - val_accuracy: 1.0000 - val_loss: 0.0169
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9699 - loss: 0.0752 - val_accuracy: 1.0000 - val_loss: 0.0166
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9666 - loss: 0.0764 - val_accuracy: 1.0000 - val_loss: 0.0167
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9699 - loss: 0.0761 - val_accuracy: 1.0000 - val_loss: 0.0162
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9699 - loss: 0.0755 - val_accuracy: 1.0000 - val_loss: 0.0162
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9666 - loss: 0.0745 - val_accuracy: 1.0000 - val_loss: 0.0161
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9666 - loss: 0.0748 - val_accuracy: 1.0000 - val_loss: 0.0164
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9699 - loss: 0.0754 - val_accuracy: 1.0000 - val_loss: 0.0160
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9699 - loss: 0.0740 - val_accuracy: 1.0000 - val_loss: 0.0155
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9699 - loss: 0.0743 - val_accuracy: 1.0000 - val_loss: 0.0154
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9666 - loss: 0.0735 - val_accuracy: 1.0000 - val_loss: 0.0154
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9699 - loss: 0.0741 - val_accuracy: 1.0000 - val_loss: 0.0152
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9699 - loss: 0.0738 - val_accuracy: 1.0000 - val_loss: 0.0153
11/11 - 0s - 10ms/step - accuracy: 0.9730 - loss: 0.0661

In [19]:
model_logit_false.predict(scaled_penguins_x)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

array([[9.99528110e-01, 9.72282469e-01, 8.70427873e-04],
       [2.60105226e-02, 9.15998757e-01, 5.77111602e-01],
       [9.99564588e-01, 9.69048679e-01, 8.74163990e-04],
       [4.15164577e-05, 2.88946092e-01, 9.92863894e-01],
       [9.99544501e-01, 9.61549163e-01, 1.01236708e-03],
       [3.17385852e-01, 9.74584758e-01, 1.66166380e-01],
       [9.11671162e-01, 9.79715884e-01, 2.65698787e-02],
       [4.18658747e-04, 4.08543766e-01, 9.75281000e-01],
       [6.87785432e-05, 3.01271290e-01, 9.90938485e-01],
       [1.97833040e-04, 3.91173422e-01, 9.82421339e-01],
       [9.73487854e-01, 9.63295400e-01, 1.55846858e-02],
       [9.99999285e-01, 9.75241363e-01, 9.28996906e-06],
       [9.83816028e-01, 9.79950249e-01, 8.08524340e-03],
       [9.99974072e-01, 9.80132639e-01, 1.02115933e-04],
       [5.52902460e-01, 9.85056221e-01, 8.79083574e-02],
       [9.99605834e-01, 9.72188771e-01, 7.71838007e-04],
       [9.99973714e-01, 9.72381532e-01, 1.22646627e-04],
       [4.84421907e-05, 2.92681128e-01, 9.92323041e-01],
       [9.99989390e-01, 9.80757117e-01, 5.46796691e-05],
       [3.09666753e-01, 9.76319194e-01, 1.62112713e-01],
       [9.97984946e-01, 9.64161694e-01, 2.67034443e-03],
       [9.99167264e-01, 9.49765325e-01, 1.76074705e-03],
       [2.49993242e-02, 8.89541924e-01, 6.25246167e-01],
       [2.82866040e-05, 2.79780924e-01, 9.94050384e-01],
       [9.99857903e-01, 9.77921486e-01, 3.41888546e-04],
       [9.99783039e-01, 9.73092377e-01, 5.05995995e-04],
       [3.00527863e-05, 2.81215757e-01, 9.93877053e-01],
       [5.82106352e-01, 9.74143624e-01, 1.07711978e-01],
       [5.47487543e-05, 2.95663983e-01, 9.91865277e-01],
       [8.85774493e-01, 9.79049206e-01, 3.26074064e-02],
       [7.22678451e-05, 3.02495599e-01, 9.90724027e-01],
       [2.55266786e-01, 9.75622952e-01, 1.80138811e-01],
       [9.99570251e-01, 9.70997512e-01, 8.36892112e-04],
       [9.99833822e-01, 9.80526209e-01, 3.55805125e-04],
       [1.21300168e-01, 9.25202012e-01, 3.93641144e-01],
       [7.63042748e-01, 9.77441430e-01, 5.98059930e-02],
       [4.23126072e-02, 8.81710827e-01, 5.83761811e-01],
       [1.23650179e-05, 2.60632396e-01, 9.95983064e-01],
       [9.99991655e-01, 9.75975156e-01, 5.23067065e-05],
       [9.99898136e-01, 9.65532005e-01, 3.45849607e-04],
       [9.99999225e-01, 9.78638947e-01, 9.55460018e-06],
       [9.99978304e-01, 9.76943851e-01, 9.77910968e-05],
       [1.89464336e-04, 3.26887757e-01, 9.85388041e-01],
       [8.79906584e-05, 3.07393372e-01, 9.89820004e-01],
       [9.99873459e-01, 9.63976920e-01, 4.10289824e-04],
       [9.98980105e-01, 9.71741021e-01, 1.48271979e-03],
       [7.21630216e-01, 9.80104566e-01, 6.45023361e-02],
       [9.99910653e-01, 9.65910256e-01, 3.14531848e-04],
       [9.99996006e-01, 9.71040785e-01, 3.51562303e-05],
       [6.04753375e-01, 9.79135275e-01, 9.18122455e-02],
       [9.99970913e-01, 9.78103101e-01, 1.16133546e-04],
       [1.04091960e-04, 3.11609149e-01, 9.88979697e-01],
       [4.49578729e-05, 2.90870488e-01, 9.92589593e-01],
       [9.99993920e-01, 9.60162818e-01, 5.24504139e-05],
       [9.99992013e-01, 9.87201035e-01, 3.63960789e-05],
       [1.36335986e-03, 5.37689567e-01, 9.46791708e-01],
       [9.99446273e-01, 9.77346241e-01, 8.71600583e-04],
       [9.99966443e-01, 9.79365170e-01, 1.23948950e-04],
       [6.57593919e-05, 3.00163209e-01, 9.91128743e-01],
       [1.10378596e-05, 2.58072376e-01, 9.96194005e-01],
       [9.43137527e-01, 9.78557587e-01, 1.99701283e-02],
       [4.14225966e-01, 9.69811320e-01, 1.57708004e-01],
       [6.91064477e-01, 9.78474796e-01, 7.35936984e-02],
       [9.99996424e-01, 9.81531799e-01, 2.55389514e-05],
       [9.99997079e-01, 9.64296818e-01, 2.89569125e-05],
       [1.53494313e-01, 9.62891400e-01, 2.70228088e-01],
       [9.99023914e-01, 9.72544193e-01, 1.41732849e-03],
       [2.63279708e-05, 2.78086871e-01, 9.94249463e-01],
       [9.99918580e-01, 9.77613866e-01, 2.36151594e-04],
       [9.90042567e-01, 9.75956261e-01, 6.38720393e-03],
       [9.99997020e-01, 9.81437683e-01, 2.28332028e-05],
       [9.99941707e-01, 9.65978920e-01, 2.35234940e-04],
       [5.73154030e-05, 2.96785206e-01, 9.91687000e-01],
       [3.72361749e-01, 9.70357001e-01, 1.65810943e-01],
       [1.02884769e-04, 3.43976229e-01, 9.88017142e-01],
       [8.02080831e-05, 3.09054822e-01, 9.90145445e-01],
       [9.99989331e-01, 9.65912044e-01, 7.43367127e-05],
       [9.99997675e-01, 9.73598063e-01, 2.29536072e-05],
       [9.99974966e-01, 9.56367433e-01, 1.51594257e-04],
       [4.79871902e-04, 3.89186502e-01, 9.75130141e-01],
       [9.99370575e-01, 9.74611461e-01, 1.00985868e-03],
       [9.99937654e-01, 9.62690890e-01, 2.58818443e-04],
       [3.94178584e-04, 4.69228715e-01, 9.72062588e-01],
       [9.99921322e-01, 9.81636345e-01, 2.07790348e-04],
       [6.12080455e-01, 9.74197805e-01, 9.97539461e-02],
       [1.72744003e-05, 2.68266231e-01, 9.95291710e-01],
       [9.99993026e-01, 9.71597314e-01, 5.06623437e-05],
       [1.93236582e-02, 8.89390111e-01, 6.50131106e-01],
       [1.17575424e-03, 5.58966160e-01, 9.47185099e-01],
       [4.74063490e-05, 2.92156130e-01, 9.92401183e-01],
       [2.37216809e-05, 2.75637031e-01, 9.94526863e-01],
       [6.65545404e-01, 9.70062375e-01, 9.29505900e-02],
       [9.99281228e-01, 9.64330912e-01, 1.32460624e-03],
       [9.99204993e-01, 9.60426271e-01, 1.49967207e-03],
       [9.99829113e-01, 9.66957927e-01, 4.80230432e-04],
       [9.99997318e-01, 9.75214005e-01, 2.45681604e-05],
       [9.99960601e-01, 9.70045626e-01, 1.68590384e-04],
       [3.51393392e-05, 2.84940749e-01, 9.93405998e-01],
       [9.97987926e-01, 9.66127574e-01, 2.58833892e-03],
       [9.99995232e-01, 9.77868736e-01, 3.42306994e-05],
       [9.99588609e-01, 9.78860974e-01, 6.86948129e-04],
       [5.08643985e-01, 9.70861793e-01, 1.35619447e-01],
       [2.26576284e-01, 9.63242590e-01, 2.32537702e-01],
       [9.99551237e-01, 9.75579619e-01, 7.86520250e-04],
       [2.60315457e-04, 3.35147142e-01, 9.83037114e-01],
       [9.99957919e-01, 9.77300227e-01, 1.52064196e-04],
       [6.37029079e-05, 2.99380302e-01, 9.91261005e-01],
       [1.13068862e-04, 3.13696086e-01, 9.88541126e-01],
       [9.99989033e-01, 9.79464531e-01, 5.79605730e-05],
       [4.98154201e-04, 3.81450593e-01, 9.75243926e-01],
       [9.99953806e-01, 9.70621943e-01, 1.85793193e-04],
       [1.89175755e-01, 9.46499348e-01, 2.96788156e-01],
       [9.53667939e-01, 9.79558766e-01, 1.68727394e-02],
       [1.01496000e-03, 4.63851482e-01, 9.60026562e-01],
       [3.28264359e-05, 2.83315092e-01, 9.93615389e-01],
       [4.63054130e-05, 2.91586071e-01, 9.92485285e-01],
       [9.99841750e-01, 9.78541553e-01, 3.62350111e-04],
       [5.86628266e-05, 2.97354817e-01, 9.91595149e-01],
       [9.87334669e-01, 9.80503917e-01, 6.73922896e-03],
       [8.57237392e-05, 3.06741446e-01, 9.89944696e-01],
       [9.99972999e-01, 9.57014024e-01, 1.58374911e-04],
       [1.39068405e-04, 3.18950534e-01, 9.87366974e-01],
       [6.19731069e-01, 9.76885080e-01, 9.27705169e-02],
       [9.99979436e-01, 9.62670505e-01, 1.22010548e-04],
       [9.99918342e-01, 9.48963940e-01, 3.68021923e-04],
       [6.11884892e-02, 9.23188746e-01, 4.72487688e-01],
       [9.99997139e-01, 9.55282331e-01, 2.97960087e-05],
       [9.99964118e-01, 9.75067437e-01, 1.43415818e-04],
       [9.98056114e-01, 9.65860367e-01, 2.53919489e-03],
       [2.22921008e-05, 2.74182677e-01, 9.94685888e-01],
       [9.99445021e-01, 9.68286216e-01, 1.04383542e-03],
       [9.99996066e-01, 9.70930934e-01, 3.47866153e-05],
       [1.19764401e-04, 3.15151870e-01, 9.88226056e-01],
       [9.99928951e-01, 9.76877213e-01, 2.19061578e-04],
       [9.99998927e-01, 9.74266291e-01, 1.24371363e-05],
       [9.99998868e-01, 9.74670231e-01, 1.32586592e-05],
       [4.13093112e-05, 2.88825452e-01, 9.92880762e-01],
       [9.84172106e-01, 9.71266508e-01, 9.62242112e-03],
       [8.22272539e-01, 9.77572203e-01, 4.72548343e-02],
       [9.99843657e-01, 9.75441813e-01, 3.85949359e-04],
       [9.99358058e-01, 9.70254242e-01, 1.11339719e-03],
       [6.35015895e-05, 2.99302369e-01, 9.91274118e-01],
       [9.99993622e-01, 9.70636070e-01, 4.85092642e-05],
       [1.31490559e-03, 7.08117843e-01, 9.20281768e-01],
       [7.96571403e-05, 3.09972197e-01, 9.90147233e-01],
       [9.10723448e-01, 9.86140490e-01, 2.20164228e-02],
       [3.50794435e-05, 2.84899950e-01, 9.93411303e-01],
       [7.61906803e-02, 9.52661335e-01, 3.73019993e-01],
       [9.41190592e-05, 3.09078664e-01, 9.89491224e-01],
       [4.37671661e-05, 2.90220976e-01, 9.92683232e-01],
       [2.47910561e-04, 3.41976136e-01, 9.83057976e-01],
       [7.66137164e-05, 3.03943902e-01, 9.90464449e-01],
       [9.99218881e-01, 9.55387712e-01, 1.58086850e-03],
       [9.98163760e-01, 9.74563658e-01, 2.08877586e-03],
       [9.98737232e-05, 3.10568452e-01, 9.89192724e-01],
       [9.46221116e-04, 5.79275191e-01, 9.49043393e-01],
       [1.43495694e-04, 3.19750249e-01, 9.87179160e-01],
       [9.99931037e-01, 9.73223805e-01, 2.32017337e-04],
       [9.58884601e-04, 4.40671206e-01, 9.62987006e-01],
       [3.88843636e-03, 6.41320109e-01, 8.99444997e-01],
       [9.99377191e-01, 9.64124978e-01, 1.20569766e-03],
       [6.54052377e-01, 9.79062080e-01, 8.06660801e-02],
       [4.43067491e-01, 9.76446509e-01, 1.32580325e-01],
       [3.05601925e-01, 9.73990381e-01, 1.71317309e-01],
       [6.40369180e-05, 2.99509078e-01, 9.91239369e-01],
       [8.25490279e-04, 5.08504987e-01, 9.59057629e-01],
       [3.99999044e-05, 2.88049430e-01, 9.92988586e-01],
       [1.61466814e-04, 3.28112870e-01, 9.86247361e-01],
       [8.27947515e-05, 3.05874288e-01, 9.90108490e-01],
       [9.98590529e-01, 9.81106043e-01, 1.49195420e-03],
       [9.99995887e-01, 9.69310582e-01, 3.69395748e-05],
       [3.58307370e-05, 2.85407007e-01, 9.93344843e-01],
       [3.45072329e-01, 9.59657848e-01, 2.02101573e-01],
       [9.99586284e-01, 9.78073359e-01, 7.03064376e-04],
       [3.71947587e-01, 9.76926446e-01, 1.45361975e-01],
       [5.34139872e-01, 9.84384835e-01, 9.26571414e-02],
       [9.99966443e-01, 9.60203946e-01, 1.75940091e-04],
       [9.99990284e-01, 9.71565247e-01, 6.33088348e-05],
       [9.99623120e-01, 9.75644052e-01, 6.97770389e-04],
       [9.99920428e-01, 9.82187629e-01, 2.06075565e-04],
       [3.58351678e-01, 9.75860298e-01, 1.51934177e-01],
       [9.99565721e-01, 9.71817732e-01, 8.30044155e-04],
       [1.74810644e-04, 3.42480004e-01, 9.85243917e-01],
       [3.72411430e-01, 9.75851774e-01, 1.48819968e-01],
       [9.99752343e-01, 9.57543015e-01, 7.06627441e-04],
       [7.15698232e-04, 4.34185445e-01, 9.67502236e-01],
       [2.70020573e-05, 2.78682977e-01, 9.94180083e-01],
       [9.99418020e-01, 9.78932500e-01, 8.67549679e-04],
       [6.54560983e-01, 9.76061881e-01, 8.59651268e-02],
       [9.99913394e-01, 9.61372495e-01, 3.29483300e-04],
       [7.79218137e-01, 9.74662244e-01, 5.97759113e-02],
       [9.97503757e-01, 9.63057876e-01, 3.13794403e-03],
       [8.61738590e-05, 3.06872189e-01, 9.89919782e-01],
       [9.36701059e-01, 9.80227172e-01, 2.06566527e-02],
       [1.35418217e-04, 3.18272650e-01, 9.87524331e-01],
       [9.99821842e-01, 9.78418350e-01, 3.93785536e-04],
       [9.99997556e-01, 9.73495841e-01, 2.40502141e-05],
       [9.99902368e-01, 9.66376781e-01, 3.31624353e-04],
       [5.08708545e-05, 2.93871343e-01, 9.92143214e-01],
       [9.99932110e-01, 9.78050530e-01, 2.06593570e-04],
       [1.87884598e-05, 2.70206511e-01, 9.95100141e-01],
       [9.99963522e-01, 9.73419607e-01, 1.50033127e-04],
       [9.74025488e-01, 9.85635996e-01, 9.39918496e-03],
       [9.99872386e-01, 9.65342879e-01, 4.04221879e-04],
       [9.99811292e-01, 9.73996878e-01, 4.51967615e-04],
       [5.22985756e-05, 2.94546038e-01, 9.92039621e-01],
       [6.59106763e-06, 2.46654555e-01, 9.97021377e-01],
       [7.48365928e-05, 3.03361356e-01, 9.90569651e-01],
       [9.51196074e-01, 9.66363072e-01, 2.26849262e-02],
       [9.99940157e-01, 9.66882646e-01, 2.36085165e-04],
       [9.99217391e-01, 9.68010366e-01, 1.32378843e-03],
       [2.30939313e-05, 2.75008947e-01, 9.94596064e-01],
       [3.06551898e-04, 3.39438021e-01, 9.81686056e-01],
       [9.99969125e-01, 9.61099029e-01, 1.64405428e-04],
       [9.99990582e-01, 9.54429150e-01, 7.53909262e-05],
       [1.11231849e-01, 9.45622504e-01, 3.54442954e-01],
       [9.99995351e-01, 9.77272987e-01, 3.41680134e-05],
       [2.48923880e-05, 2.76767492e-01, 9.94400382e-01],
       [9.99980390e-01, 9.62838233e-01, 1.17937991e-04],
       [7.50758469e-01, 9.72448468e-01, 6.89123124e-02],
       [7.83522487e-01, 9.63850915e-01, 7.02521950e-02],
       [4.32892978e-01, 9.74821687e-01, 1.39438301e-01],
       [9.83967185e-01, 9.81363654e-01, 7.73171056e-03],
       [9.14860648e-05, 3.08367848e-01, 9.89631057e-01],
       [9.66484070e-01, 9.76428807e-01, 1.45108877e-02],
       [5.44470313e-05, 2.95528948e-01, 9.91886497e-01],
       [6.88578148e-05, 3.01299781e-01, 9.90933537e-01],
       [9.97194767e-01, 9.70003366e-01, 3.03877401e-03],
       [1.14193920e-03, 4.63694692e-01, 9.58164275e-01],
       [9.99990463e-01, 9.78322744e-01, 5.41524969e-05],
       [9.99709427e-01, 9.62669551e-01, 7.34731846e-04],
       [7.63193064e-04, 5.92723012e-01, 9.51570690e-01],
       [9.99861479e-01, 9.68124628e-01, 4.08577500e-04],
       [2.26863340e-04, 3.31558377e-01, 9.84097481e-01],
       [9.99647379e-01, 9.71512079e-01, 7.24926300e-04],
       [8.06199459e-05, 3.05211216e-01, 9.90232050e-01],
       [1.68555602e-02, 8.88975978e-01, 6.63429499e-01],
       [9.99933422e-01, 9.82838392e-01, 1.79076320e-04],
       [8.75358403e-01, 9.85527039e-01, 2.88095921e-02],
       [2.20694230e-03, 5.58273196e-01, 9.32930112e-01],
       [3.37753505e-01, 9.63635862e-01, 1.93770096e-01],
       [9.99674380e-01, 9.78533804e-01, 5.91018703e-04],
       [7.46656588e-05, 3.03304672e-01, 9.90579784e-01],
       [1.40766118e-04, 3.63997787e-01, 9.85681415e-01],
       [5.80765955e-05, 2.97108531e-01, 9.91634965e-01],
       [9.99995887e-01, 9.75158036e-01, 3.30098264e-05],
       [9.99280035e-01, 9.75677073e-01, 1.08133245e-03],
       [9.99523044e-01, 9.81628537e-01, 7.05197570e-04],
       [1.54955755e-03, 6.50405526e-01, 9.26967025e-01],
       [6.84876868e-04, 4.92504925e-01, 9.63333249e-01],
       [5.67983443e-05, 2.96563238e-01, 9.91722584e-01],
       [9.89165246e-01, 9.79663789e-01, 6.19454542e-03],
       [5.45788098e-05, 2.95588046e-01, 9.91877258e-01],
       [9.99721110e-01, 9.73021269e-01, 6.00703817e-04],
       [9.99908447e-01, 9.70446646e-01, 2.96301267e-04],
       [1.15973223e-03, 4.90058273e-01, 9.55240846e-01],
       [9.99588728e-01, 9.51324582e-01, 1.07317639e-03],
       [9.99836624e-01, 9.77185488e-01, 3.82487313e-04],
       [9.99998569e-01, 9.77718472e-01, 1.50236601e-05],
       [9.99999344e-01, 9.78204191e-01, 8.26564155e-06],
       [9.99098063e-01, 9.83502150e-01, 1.02637720e-03],
       [3.81751102e-04, 4.46974993e-01, 9.73839879e-01],
       [9.99903738e-01, 9.64930177e-01, 3.35991295e-04],
       [5.27581573e-01, 9.83160436e-01, 9.75946561e-02],
       [9.90072012e-01, 9.82140362e-01, 5.45197306e-03],
       [2.92645942e-04, 3.38216871e-01, 9.82080102e-01],
       [3.37745667e-01, 9.64954615e-01, 1.90156788e-01],
       [7.00683959e-05, 3.01730603e-01, 9.90858555e-01],
       [6.37451958e-05, 2.99396634e-01, 9.91258264e-01],
       [7.12401161e-05, 3.02140921e-01, 9.90786612e-01],
       [1.49764836e-01, 9.52625990e-01, 3.04370165e-01],
       [3.12131335e-04, 4.29295689e-01, 9.76851583e-01],
       [9.78928566e-01, 9.87764478e-01, 7.48669403e-03],
       [7.68518984e-01, 9.77640748e-01, 5.83933741e-02],
       [4.58649933e-01, 9.76695895e-01, 1.28925145e-01],
       [3.53247277e-04, 4.33120698e-01, 9.75462556e-01],
       [1.13542956e-04, 3.13801825e-01, 9.88518536e-01],
       [9.99955475e-01, 9.80269909e-01, 1.46657520e-04],
       [2.33963183e-05, 2.75313467e-01, 9.94562626e-01],
       [5.61085035e-05, 2.96264082e-01, 9.91770327e-01],
       [9.90766493e-05, 3.10367048e-01, 9.89233494e-01],
       [9.96976852e-01, 9.78664756e-01, 2.66890740e-03],
       [9.99992788e-01, 9.64322686e-01, 5.86716669e-05],
       [9.97363985e-01, 9.79704082e-01, 2.36880663e-03],
       [9.99742985e-01, 9.64632392e-01, 6.56791846e-04],
       [9.99997199e-01, 9.65389490e-01, 2.77749496e-05],
       [1.39278476e-04, 3.22981387e-01, 9.87218142e-01],
       [9.99939024e-01, 9.67248797e-01, 2.37647066e-04],
       [5.17963854e-05, 2.94310719e-01, 9.92075861e-01],
       [9.99728680e-01, 9.63283539e-01, 6.95092021e-04],
       [9.99983788e-01, 9.66255903e-01, 9.83470527e-05],
       [2.79260974e-04, 3.49258035e-01, 9.81889188e-01],
       [2.10107919e-05, 2.72801995e-01, 9.94833112e-01],
       [9.99999344e-01, 9.72673953e-01, 8.74265061e-06],
       [9.99965787e-01, 9.73686218e-01, 1.42849007e-04],
       [5.61881542e-01, 9.88476038e-01, 7.48515949e-02],
       [7.34006971e-05, 3.02880973e-01, 9.90655601e-01],
       [2.05605686e-01, 9.64781284e-01, 2.36712679e-01],
       [9.90058720e-01, 9.79292989e-01, 5.89762162e-03],
       [3.77204239e-01, 9.66549397e-01, 1.75365418e-01],
       [1.13583250e-04, 3.13810766e-01, 9.88516629e-01],
       [9.99978423e-01, 9.70148087e-01, 1.11769506e-04],
       [9.99406397e-01, 9.78190303e-01, 8.95467238e-04],
       [9.96781164e-05, 3.10519129e-01, 9.89202678e-01],
       [9.20987004e-05, 3.08534980e-01, 9.89598334e-01],
       [2.55139470e-01, 9.58564520e-01, 2.34765738e-01],
       [9.84868821e-05, 3.10217083e-01, 9.89263773e-01],
       [3.25518800e-03, 6.15928233e-01, 9.11301434e-01],
       [9.99991298e-01, 9.69069958e-01, 6.15354875e-05],
       [9.99999285e-01, 9.69411969e-01, 9.43103714e-06],
       [7.90712147e-05, 3.04728568e-01, 9.90321159e-01],
       [3.24004388e-04, 3.40897232e-01, 9.81204987e-01],
       [9.99927104e-01, 9.63577151e-01, 2.83932633e-04],
       [2.62665970e-04, 4.27689165e-01, 9.78466988e-01],
       [7.71755695e-01, 9.81957972e-01, 5.18502183e-02],
       [1.16414718e-04, 3.14433545e-01, 9.88382459e-01],
       [4.52856541e-01, 9.81924057e-01, 1.13160342e-01],
       [5.01002251e-05, 2.93499619e-01, 9.92199779e-01],
       [2.66153216e-01, 9.69543755e-01, 1.97969824e-01],
       [9.34493146e-05, 3.08899701e-01, 9.89526570e-01],
       [9.99982417e-01, 9.74069178e-01, 9.02772153e-05],
       [4.73481123e-05, 2.92126298e-01, 9.92405653e-01],
       [9.99974370e-01, 9.64846253e-01, 1.37198469e-04],
       [9.99852240e-01, 9.59269941e-01, 4.86822828e-04],
       [3.28396818e-05, 2.83324718e-01, 9.93614137e-01],
       [9.99151826e-01, 9.63032484e-01, 1.51059125e-03],
       [8.23732242e-02, 9.57837403e-01, 3.48098367e-01],
       [9.99997735e-01, 9.79838431e-01, 1.95458961e-05],
       [2.89769145e-04, 3.37957293e-01, 9.82162833e-01],
       [9.99996722e-01, 9.65181708e-01, 3.16200749e-05],
       [9.99103844e-01, 9.79220569e-01, 1.15400122e-03],
       [3.00489843e-01, 9.76570189e-01, 1.63600996e-01],
       [9.99911249e-01, 9.72098172e-01, 2.81457062e-04]], dtype=float32)

In [20]:
penguins_y

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0,
       0, 1, 0], dtype=int8)